from typing import Any

from app.graph.state import GMAGraphState


def append_trace(state: GMAGraphState, node: str, message: str) -> list[dict[str, Any]]:
    return [
        *state["trace"],
        {
            "node": node,
            "message": message,
        },
    ]


def start_node(state: GMAGraphState) -> dict[str, Any]:
    return {
        "status": "started",
        "trace": append_trace(state, "start", "Mock workflow started."),
    }


def collect_sources_mock_node(state: GMAGraphState) -> dict[str, Any]:
    source_bundle = {
        "short_description": f"Mock short description for {state['game_name']}.",
        "detailed_description": "Mock detailed description reserved for the future Tavily node.",
        "review_summary": "Mock review summary.",
        "page_text": "Mock Steam page text.",
        "source_urls": [state["steam_url"]],
        "extraction_notes": "This source bundle was generated by a mock node.",
    }

    return {
        "source_bundle": source_bundle,
        "status": "sources_collected",
        "trace": append_trace(state, "collect_sources_mock", "Mock source bundle collected."),
    }


def retrieve_grs_context_mock_node(state: GMAGraphState) -> dict[str, Any]:
    retrieved_context = {
        "tag_count": 20,
        "weight_scale": "1-5",
        "context_notes": "Mock GRS context. Stage 5 will read the modeling_context rule pack.",
    }

    return {
        "retrieved_context": retrieved_context,
        "status": "context_retrieved",
        "trace": append_trace(state, "retrieve_grs_context_mock", "Mock GRS context retrieved."),
    }


def model_game_tags_mock_node(state: GMAGraphState) -> dict[str, Any]:
    modeling_result = {
        "overall_summary": f"Mock modeling result for {state['game_name']}.",
        "selected_existing_tags": [
            {
                "tag_code": "combat",
                "suggested_weight": 4,
                "confidence": 0.8,
                "evidence_snippets": ["Mock evidence from collected source bundle."],
                "reason": "Mock reason showing how a future LLM output will be shaped.",
            }
        ],
        "warnings": [],
    }

    return {
        "modeling_result": modeling_result,
        "status": "modeled",
        "trace": append_trace(state, "model_game_tags_mock", "Mock modeling result generated."),
    }


def validate_result_mock_node(state: GMAGraphState) -> dict[str, Any]:
    validation_result = {
        "is_valid": True,
        "errors": [],
        "warnings": [],
    }

    return {
        "validation_result": validation_result,
        "status": "validated",
        "trace": append_trace(state, "validate_result_mock", "Mock validation passed."),
    }


def finish_node(state: GMAGraphState) -> dict[str, Any]:
    return {
        "status": "finished",
        "trace": append_trace(state, "finish", "Mock workflow finished."),
    }
