from typing import Any

from app.chains.modeling_chain import ModelingChain
from app.graph.state import GMAGraphState
from app.services.grs_context.grs_context_service import GRSContextService
from app.services.source_collection.source_collection_service import SourceCollectionService


def append_trace(state: GMAGraphState, node: str, message: str) -> list[dict[str, Any]]:
    return [
        *state["trace"],
        {
            "node": node,
            "message": message,
        },
    ]


def start_node(state: GMAGraphState) -> dict[str, Any]:
    return {
        "status": "started",
        "trace": append_trace(state, "start", "Mock workflow started."),
    }


def collect_sources_mock_node(state: GMAGraphState) -> dict[str, Any]:
    source_bundle = {
        "short_description": f"Mock short description for {state['game_name']}.",
        "detailed_description": "Mock detailed description reserved for the Steam source collection node.",
        "review_summary": "Mock review summary.",
        "page_text": "Mock Steam page text.",
        "source_urls": [state["steam_url"]],
        "extraction_notes": "This source bundle was generated by a mock node.",
    }

    return {
        "source_bundle": source_bundle,
        "status": "sources_collected",
        "trace": append_trace(state, "collect_sources_mock", "Mock source bundle collected."),
    }


def collect_sources_node(state: GMAGraphState) -> dict[str, Any]:
    source_bundle = SourceCollectionService().collect_sources(
        game_name=state["game_name"],
        steam_url=state["steam_url"],
    )

    return {
        "source_bundle": source_bundle.model_dump(),
        "status": "sources_collected",
        "trace": append_trace(
            state,
            "collect_sources",
            "Source bundle collected from Steam official data.",
        ),
    }


def retrieve_grs_context_mock_node(state: GMAGraphState) -> dict[str, Any]:
    retrieved_context = {
        "tag_count": 20,
        "weight_scale": "1-5",
        "context_notes": "Mock GRS context. Stage 5 will read the modeling_context rule pack.",
    }

    return {
        "retrieved_context": retrieved_context,
        "status": "context_retrieved",
        "trace": append_trace(state, "retrieve_grs_context_mock", "Mock GRS context retrieved."),
    }


def retrieve_grs_context_node(state: GMAGraphState) -> dict[str, Any]:
    retrieved_context = GRSContextService().retrieve_context()

    return {
        "retrieved_context": retrieved_context.model_dump(),
        "status": "context_retrieved",
        "trace": append_trace(state, "retrieve_grs_context", "GRS rule pack context retrieved."),
    }


def model_game_tags_mock_node(state: GMAGraphState) -> dict[str, Any]:
    modeling_result = {
        "overall_summary": f"Mock modeling result for {state['game_name']}.",
        "selected_existing_tags": [
            {
                "tag_code": "combat",
                "suggested_weight": 4,
                "confidence": 0.8,
                "evidence_snippets": [
                    {
                        "en": "Mock evidence from collected source bundle.",
                        "zh": "来自已收集 source bundle 的模拟证据。",
                    }
                ],
                "reason": {
                    "en": "Mock reason showing how a future LLM output will be shaped.",
                    "zh": "模拟理由，用来展示未来 LLM 输出的结构。",
                },
            }
        ],
        "warnings": [],
    }

    return {
        "modeling_result": modeling_result,
        "status": "modeled",
        "trace": append_trace(state, "model_game_tags_mock", "Mock modeling result generated."),
    }


def model_game_tags_node(state: GMAGraphState) -> dict[str, Any]:
    if state["source_bundle"] is None:
        return {
            "status": "failed",
            "errors": [*state["errors"], "source_bundle is required before modeling."],
            "trace": append_trace(state, "model_game_tags", "Modeling failed because source_bundle is missing."),
        }
    if state["retrieved_context"] is None:
        return {
            "status": "failed",
            "errors": [*state["errors"], "retrieved_context is required before modeling."],
            "trace": append_trace(state, "model_game_tags", "Modeling failed because retrieved_context is missing."),
        }

    try:
        modeling_result = ModelingChain().invoke(
            game_name=state["game_name"],
            steam_url=state["steam_url"],
            source_bundle=state["source_bundle"],
            retrieved_context=state["retrieved_context"],
        )
    except Exception as error:
        return {
            "status": "failed",
            "errors": [*state["errors"], f"model_game_tags failed: {error}"],
            "trace": append_trace(
                state,
                "model_game_tags",
                "Modeling failed during the LLM structured output step.",
            ),
        }

    return {
        "modeling_result": modeling_result.model_dump(),
        "status": "modeled",
        "trace": append_trace(state, "model_game_tags", "Structured modeling result generated."),
    }


def validate_result_mock_node(state: GMAGraphState) -> dict[str, Any]:
    validation_result = {
        "is_valid": True,
        "errors": [],
        "warnings": [],
    }

    return {
        "validation_result": validation_result,
        "status": "validated",
        "trace": append_trace(state, "validate_result_mock", "Mock validation passed."),
    }


def finish_node(state: GMAGraphState) -> dict[str, Any]:
    return {
        "status": "finished",
        "trace": append_trace(state, "finish", "Mock workflow finished."),
    }
